server:
  port: 8083
spring:
  application:
    name: provider0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: yangtao
    password: 123
#    url: jdbc:mysql://127.0.0.1/demo?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://192.168.1.106:3306/demo?useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.gjt.mm.mysql.Driver
  devtools:
    restart:
      enabled: true  #是否支持热部署
eureka:
  client:
    service-url:
      #      defaultZone: http://user:123@peer2:8762/eureka/,http://user:123@peer1:8761/eureka/
      defaultZone: http://root:123456@localhost:8080/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  type-aliases-package: demo.service2
  mapper-locations: classpath:mapper/*.xml
#security:
#  user:
#    name: service
#    password: 123456
#  basic:
#    enabled: true