package cn.demo.service1.pojo;

import java.math.BigDecimal;

public class Demo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEMO.ID
     *
     * @mbggenerated
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEMO.CONTEXT
     *
     * @mbggenerated
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEMO.ID
     *
     * @return the value of DEMO.ID
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEMO.ID
     *
     * @param id the value for DEMO.ID
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEMO.CONTEXT
     *
     * @return the value of DEMO.CONTEXT
     * @mbggenerated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEMO.CONTEXT
     *
     * @param context the value for DEMO.CONTEXT
     * @mbggenerated
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}